"""Xuất CUE sheet, tracklist người đọc được và JSON metadata."""
import json
from datetime import datetime
from pathlib import Path

import console  # noqa: F401 - bật UTF-8 output khi import

CUE_FRAMES_PER_SECOND = 75
DEFAULT_TITLE = "Meditation Mix"
# 3 file metadata cố tình chỉ dùng ASCII để mở được bằng mọi editor/player.
FILE_ENCODING = "utf-8"


def seconds_to_cue_time(seconds: float) -> str:
    """CUE time: MM:SS:FF (FF = frame, 1 frame = 1/75 giây). Phút KHÔNG wrap."""
    total = max(float(seconds), 0.0)
    minutes = int(total // 60)
    secs = int(total % 60)
    frames = min(int((total % 1) * CUE_FRAMES_PER_SECOND), CUE_FRAMES_PER_SECOND - 1)
    return f"{minutes:02d}:{secs:02d}:{frames:02d}"


def seconds_to_clock(seconds: float) -> str:
    """MM:SS cho tracklist / JSON."""
    total = int(max(float(seconds), 0.0))
    return f"{total // 60:02d}:{total % 60:02d}"


def _quality_line(sample_rate: int, bit_depth: int, channels: int) -> str:
    depth = "32-bit float" if int(bit_depth) == 32 else f"{int(bit_depth)}-bit"
    layout = {1: "Mono", 2: "Stereo"}.get(channels, f"{channels}ch")
    return f"{sample_rate} Hz / {depth} / {layout}"


def _safe_title(name: str) -> str:
    """CUE dùng dấu " để bao title nên không cho phép " bên trong."""
    return str(name).replace('"', "'")


def _normalize(timestamps: list[dict]) -> list[dict]:
    entries = []
    for i, stamp in enumerate(timestamps):
        start = float(stamp.get("start_seconds", 0.0))
        end = float(stamp.get("end_seconds", start))
        entries.append({
            "index": i + 1,
            "name": str(stamp.get("name", f"Track {i + 1}")),
            "source_file": str(stamp.get("source_file", "")),
            "start_seconds": start,
            "end_seconds": end,
            "duration_seconds": max(end - start, 0.0),
            "start_formatted": seconds_to_clock(start),
            "end_formatted": seconds_to_clock(end),
        })
    return entries


def _write_cue(path: Path, wav_name: str, entries: list[dict], title: str) -> None:
    lines = [f'TITLE "{_safe_title(title)}"', f'FILE "{wav_name}" WAVE']
    for entry in entries:
        lines.append(f"  TRACK {entry['index']:02d} AUDIO")
        lines.append(f"    TITLE \"{_safe_title(entry['name'])}\"")
        lines.append(f"    INDEX 01 {seconds_to_cue_time(entry['start_seconds'])}")
    path.write_text("\n".join(lines) + "\n", encoding=FILE_ENCODING)


def _write_tracklist(path: Path, entries: list[dict], title: str,
                     total_duration_sec: float, sample_rate: int,
                     bit_depth: int, channels: int, generated_at: datetime) -> None:
    total = int(total_duration_sec)
    name_width = max((len(e["name"]) for e in entries), default=20) + 2
    lines = [
        f"=== {title} ===",
        f"Duration : {total // 60} min {total % 60:02d} sec",
        f"Generated: {generated_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"Quality  : {_quality_line(sample_rate, bit_depth, channels)}",
        f"Tracks   : {len(entries)}",
        "",
    ]
    for entry in entries:
        lines.append(f"{entry['start_formatted']} - {entry['name']:<{name_width}}"
                     f"[source: {entry['source_file']}]")
    lines += ["", "(Generated by MeditationMixer)"]
    path.write_text("\n".join(lines) + "\n", encoding=FILE_ENCODING)


def _write_json(path: Path, entries: list[dict], title: str,
                total_duration_sec: float, sample_rate: int, bit_depth: int,
                channels: int, crossfade_sec: float, generated_at: datetime) -> None:
    payload = {
        "title": title,
        "generated_at": generated_at.isoformat(),
        "audio": {
            "total_duration_seconds": float(total_duration_sec),
            "sample_rate": int(sample_rate),
            "bit_depth": int(bit_depth),
            "channels": int(channels),
            "crossfade_seconds": float(crossfade_sec),
        },
        "tracks": entries,
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding=FILE_ENCODING)


def write_metadata(
    timestamps: list[dict],
    output_wav_path: str,
    total_duration_sec: float,
    sample_rate: int,
    bit_depth: int,
    crossfade_sec: float,
    channels: int = 2,
    title: str = DEFAULT_TITLE,
) -> dict[str, str]:
    """Ghi <stem>.cue, <stem>_tracklist.txt, <stem>_info.json cạnh file WAV."""
    wav_path = Path(output_wav_path)
    stem, folder = wav_path.stem, wav_path.parent
    entries = _normalize(timestamps)
    generated_at = datetime.now()

    cue_path = folder / f"{stem}.cue"
    txt_path = folder / f"{stem}_tracklist.txt"
    json_path = folder / f"{stem}_info.json"

    _write_cue(cue_path, wav_path.name, entries, title)
    _write_tracklist(txt_path, entries, title, total_duration_sec,
                     sample_rate, bit_depth, channels, generated_at)
    _write_json(json_path, entries, title, total_duration_sec, sample_rate,
                bit_depth, channels, crossfade_sec, generated_at)

    return {"cue": str(cue_path), "tracklist": str(txt_path), "json": str(json_path)}
